### ISSUE TITLE
Add config to enable embedded JFRd

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-jfr-core#168]
When the JVM starts and the java agent loads, jfr will be on by default. Lets add a config to the agent so JFRd can be disabled. Maybe the config could be structured  like this:

```
common:
  jfr:
    enabled: false
    <future configs>: 
```
