### ISSUE TITLE
Support for annotating/decorating the JFR event data with custom labels from the Java Agent

### ISSUE THREAD

**Issue by akrrev** [newrelic/newrelic-jfr-core#271]
## Is your feature request related to a problem? Please describe.
When running JFR profiliing through New Relic's Java Agent, I don't have any of the custom attributes/labels from the Java agent configuration in the ingested data, 

Example configuration:
```yaml
common: &default_settings

  license_key: xxxxxxxxxxxxxxxx
  agent_enabled: true
  app_name: 'My Service (environment)'
  high_security: false
  enable_auto_transaction_naming: true

```

## Feature Description
Either automatically include or add a flag to control whether custom attributes (custom labels) should be attached to the JFR events.

A clear and concise description of the feature you want or need.

## Describe Alternatives
Currently, i only think of pipeline control, as the only potential way to 
A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to?

## Additional context
This looks very similar to the missing custom attributes/labels in logs forwarded via the Java agent, which was fixed fairly recently: 
http://github.com/newrelic/newrelic-java-agent/issues/2037 

## Priority
Really Want -> Must Have

I would assume that custom attributes/labels that can be set in the global configuration for the Java agent would be utilized in the "integration/features", the agent provides - such as JFR.
